# Generated by Django 5.2.4 on 2025-07-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0004_remove_accident_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accident_images/'),
        ),
    ]
