# Generated by Django 5.2.4 on 2025-07-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0005_accident_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='hospital_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='accident',
            name='police_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
